---
# tasks file for roles/install_prometheus_centos

  - name: Nginx installation
    yum:
      name: nginx
      state: latest
      update_cache: yes

  - name: Starting nginx
    service:
      name: nginx
      state: started

  - name: Creating /etc/prometheus
    file:
      path: /etc/prometheus
      state: directory
      mode: '0755'

  - name: Creating /var/lib/prometheus
    file:
      path: /var/lib/prometheus
      state: directory
      mode: '0755'

  - name: Creating /var/log/prometheus
    file:
      path: /var/log/prometheus
      state: directory
      mode: '0755'

  - name: Creating /var/run/prometheus
    file:
      path: /var/run/prometheus
      state: directory
      mode: '0755'

  - name: Unarchiving Prometheus
    unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v2.2.1/prometheus-2.2.1.linux-amd64.tar.gz"
      dest: /tmp/
      remote_src: yes
    register: prometheus_download

  - name: Copying prometheus to /usr/local/bin
    shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus /usr/local/bin/"
    when: prometheus_download.changed

  - name: Copying promtool to /usr/local/bin
    shell: "cp /tmp/prometheus-2.2.1.linux-amd64/promtool /usr/local/bin/"
    when: prometheus_download.changed

  - name: Prometheus execute
    file:
      path: /usr/local/bin/prometheus
      mode: u+x,g+x,o+x

  - name: Promtool execute
    file:
      path: /usr/local/bin/promtool
      mode: u+x,g+x,o+x

  - name: Copying prometheus.yml to /etc/prometheus
    shell: "cp /tmp/prometheus-2.2.1.linux-amd64/prometheus.yml /etc/prometheus/"
    when: prometheus_download.changed

  - name: Copying consoles to /etc/prometheus
    shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/consoles /etc/prometheus/"
    when: prometheus_download.changed

  - name: Copying console_libraries to /etc/prometheus
    shell: "cp -r /tmp/prometheus-2.2.1.linux-amd64/console_libraries /etc/prometheus/"

  - name: Copying prometheus.service
    copy:
      src: prometheus.service
      dest: /etc/systemd/system/prometheus.service
      mode: '0755'

  - name: Starting prometheus
    service:
      name: prometheus
      state: started
      enabled: yes

  - name: Stopping firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
