---
# tasks file for roles/configure_elk_docker_centos

  - name: Pulling elasticsearch image
    docker_image:
      name: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      source: pull

  - name: Pulling kibana's image
    docker_image:
      name: docker.elastic.co/kibana/kibana:7.10.1
      source: pull

  - name: Pulling logstash's image
    docker_image:
      name: docker.elastic.co/logstash/logstash:7.10.1
      source: pull

  - name: iptables -X
    shell: iptables -X

  - name: iptables -F
    shell: iptables -F

  - name: Restart Docker
    service:
      name: docker
      state: restarted

  - name: Creating the container for elasticsearch
    docker_container:
      name: elasticsearch
      image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
      env:
        discovery.type: "single-node"
      ports:
        - "9200:9200"
        - "9300:9300"

  - name: Creating the container for kibana
    docker_container:
      name: kibana
      image: docker.elastic.co/kibana/kibana:7.10.1
      links: "elasticsearch:elasticsearch"
      ports:
        - "5601:5601"

  - name: Creating the container for logstash
    docker_container:
      name: logstash
      image: docker.elastic.co/logstash/logstash:7.10.1
      links: "elasticsearch:elasticsearch"
      ports:
        - "5044:5044"
