---
# tasks file for roles/installing_grafana_opensuse

  - name: Installing grafana
    zypper:
      name: 'https://download.opensuse.org/repositories/openSUSE:/Factory/standard/x86_64/grafana-7.3.1-1.1.x86_64.rpm'
      state: present

  - name: Starting grafana
    service:
      name: grafana-server
      state: started
      enabled: yes

  - name: Stopping firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
