---
# tasks file for roles/installing_httpd_opensuse

  - name: Installing apache2
    zypper:
      name:
        - apache2
        - apache2-prefork
        - apache2-utils
        - libapr1
        - libapr-util1
        - libgc1
        - system-user-wwwrun
        - w3m
      state: latest
      update_cache: yes

  - name: Starting Apache2 service
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Stopping firewall
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Copying index.html
    copy:
      src: index.html
      dest: /srv/www/htdocs/index.html
      owner: wwwrun
      group: wwwrun
      mode: '0755'

  - name: Restarting Apache2
    service:
      name: apache2
      state: restarted
