---
# tasks file for roles/install_kibana_ubuntu

  - name: Installing Kibana
    apt:
      name: kibana
      state: present
      update_cache: yes

  - name: Updating config file to allow outside access
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.host:'
      line: 'server.host: 0.0.0.0'

  - name: Defining the server port
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.port:'
      line: 'server.port: 5601'

  - name: Defining Elasticsearch URL
    lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.hosts:'
      line: 'elasticsearch.hosts: "https://localhost:9200"'

  - name: Starting kibana
    service:
      name: kibana
      state: started
