---
# tasks file for roles/installing_grafana_debian

  - name: Installing gnupg, apt-transport-https, software-properties-common
    apt:
      name:
        - gnupg
        - apt-transport-https
        - software-properties-common
      state: present
      update_cache: yes

  - name: Adding the apt key
    apt_key:
      url: "https://packages.grafana.com/gpg.key"
      state: present

  - name: Adding the repository
    apt_repository:
      repo: "deb https://packages.grafana.com/oss/deb stable main"
      state: present
      filename: grafana.list

  - name: Installing grafana
    apt:
      name: grafana
      state: latest
      update_cache: yes

  - name: Starting grafana
    service:
      name: grafana-server
      state: started
      enabled: yes
