---
# tasks file for roles/install_grafana_centos

  - name: Adding the repository
    copy:
      src: grafana.repo
      dest: "/etc/yum.repos.d/grafana.repo"
      mode: "0755"

  - name: Installing grafana
    yum:
      name: grafana
      state: latest
      update_cache: yes

  - name: Starting grafana
    service:
      name: grafana-server
      state: started
      enabled: yes

  - name: Stopping firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
